var arrLang = {
    'en': {
        'Itme_HOME': 'HOME',
        'Itme_PROFILE': 'PROFILE',
        'Itme_SKILLS': 'SKILLS',
        'Itme_PORTFOLIO': 'PORTFOLIO',
        'Itme_CONTACT': 'CONTACT',
        'PROFILE_Hi': 'Hi!',
        'PROFILE_myName': 'I\'m Kevin Lin',
        'PROFILE_Saying': 'Let\'s make a better design for the product.',
        'PROFILE_Education_title': 'Education',
        'PROFILE_Experience_title': 'Experience',
        'PROFILE_Education1': ' • Da-Yeh University CSIE.',
        'PROFILE_Personality_1': 'Have passion to learn and programming.',
        'PROFILE_Personality_2': 'Happy to accept challenges and perseverance.',
        'PROFILE_Personality_3': 'Love design and solve problems.',
        'RESUME_Experience_1': ' • Jabil Green Point. Jul 2015 - Jun 2016',
        'RESUME_Experience_2': ' • JabilJabil Green Point. Jul 2016 - Nov 2016',
        'RESUME_Experience_3': ' • Republic of China Army Dec 2016 - Mar 2017',
        'RESUME_Experience_4': ' • Jabil Green Point Apr 2017 - Present',
        'RESUME_skills': 'Skill Sets',
        'RESUME_skills_front_end': 'Front End',
        'RESUME_skills_back_end': 'Back End',
        'RESUME_skills_others': 'Others',
        'RESUME_HTML_content_1': 'Familiar with 「<div>」 typesetting .',
        'RESUME_HTML_content_2': 'Familiar with 「<table>」 typesetting .',
        'RESUME_HTML_content_3': 'Understand typesetting with 「CSS grid」.',
        'RESUME_CSS_content_1': 'Familiar with the layout design, developed RWD.',
        'RESUME_CSS_content_2': 'Familiar with attributes and 「UI」 beautification (optimization).',
        'RESUME_CSS_content_3': 'Can making Module components in conjunction with 「JS」.',
        'RESUME_JS_content_1': 'Interactive function development, serial connection backend.',
        'RESUME_JS_content_2': 'Can making Module components in conjunction with 「CSS」.',
        'RESUME_JS_content_3': 'Familiar with 「JQuery」, understand 「Vue.js」.',
        'RESUME_C#_content_1': 'Concatenate the front end.',
        'RESUME_C#_content_2': 'Realize the 「KEYENCE PLC」 reading and writing program.',
        'RESUME_C#_content_3': 'Realize the data simulation generator.',
        'RESUME_Golang_content_1': 'Concatenate the front end.',
        'RESUME_Golang_content_2': 'Realize make a crawler program. (Taiwan-bank exchange rate)',
        'RESUME_Java_content': 'Make a forum web with 「JSP」.',
        'RESUME_DB_content_1': 'Familiar with 「SQL」 command.',
        'RESUME_DB_content_2': 'Familiar with 「Postgres」 and 「SQL Server」 management.',
        'RESUME_Git_content': 'Familiar with basic command, use 「Github」.',
        'RESUME_UX_content_1': 'Understand 「The UI Stack」.',
        'RESUME_UX_content_2': 'Focus on performance and simple design.',
        'RESUME_summary': 'Summary：',
        'RESUME_front_end_summary_1': 'More than 2 years of full-end experience.',
        'RESUME_front_end_summary_2': 'Realize with「RWD」,「Multilingual」 and 「EIP」.',
        'RESUME_back_end_summary_1': 'More than 2 years of full-end experience.',
        'RESUME_back_end_summary_2': 'Realize with 「Web API」、「web crawler」、「Web Server」。',
        'RESUME_others_summary_1': 'More than 2 years of experience in managing the database.',
        'RESUME_others_summary_2': 'Self-learning.',
        'RESUME_others_summary_3': 'Git basic control.',
        'CONTACT_thx_info_title': 'Thank you for visiting.',
        'CONTACT_thx_info_content': '希望你會喜歡我的，如果有任何問題，歡迎與我聯繫。-Kevin Lin.',
        'CONTACT_thx_info_signature': '-Kevin Lin.',
    },
    'zh-tw': {
        'Itme_HOME': '首頁',
        'Itme_PROFILE': '簡介',
        'Itme_SKILLS': '技能',
        'Itme_PORTFOLIO': '作品集',
        'Itme_CONTACT': '與我聯繫',
        'PROFILE_Hi': '嗨!',
        'PROFILE_myName': '我叫林建成',
        'PROFILE_Saying': '讓我們為產品做出更好的設計。',
        'PROFILE_Education_title': '學歷',
        'PROFILE_Experience_title': '經歷',
        'PROFILE_Education1': ' • 大葉大學資訊工程系',
        'PROFILE_Personality_1': '對學習和編程充滿熱情',
        'PROFILE_Personality_2': '樂於接受挑戰和堅毅的心志',
        'PROFILE_Personality_3': '喜愛設計以及解決問題',
        'RESUME_Experience_1': ' • 捷普綠點擔任「實習工程師」。 2015年7月 - 2016年6月',
        'RESUME_Experience_2': ' • 捷普綠點擔任「全端工程師」。 2016年7月 - 2016年11月',
        'RESUME_Experience_3': ' • 國軍 Online。 2016年12月 - 2017年3月',
        'RESUME_Experience_4': ' • 捷普綠點擔任「全端工程師」。 2017年4月 - 至今',
        'RESUME_skills': '技能',
        'RESUME_skills_front_end': '前端',
        'RESUME_skills_back_end': '後端',
        'RESUME_skills_others': '其他',
        'RESUME_HTML_content_1': '熟悉且能使用「<div>」進行切版。',
        'RESUME_HTML_content_2': '熟悉且能使用「<table>」進行切版。',
        'RESUME_HTML_content_3': '懂且能使用「CSS grid」切版。',
        'RESUME_CSS_content_1': '排板設計，懂「RWD」且開發過。',
        'RESUME_CSS_content_2': '熟悉屬性且能「UI」美化(優化)。',
        'RESUME_CSS_content_3': '可以配合「JS」開發模組元件。',
        'RESUME_JS_content_1': '互動功能開發、串接後端。',
        'RESUME_JS_content_2': '可以配合「CSS」開發模組元件',
        'RESUME_JS_content_3': '熟悉「JQuery」、懂「Vue.js」',
        'RESUME_C#_content_1': '串接前端。',
        'RESUME_C#_content_2': '實作出「KEYENCE PLC」讀寫程式。',
        'RESUME_C#_content_3': '實作出動態資料模擬生成程式。',
        'RESUME_Golang_content_1': '串接前端。',
        'RESUME_Golang_content_2': '實作出爬蟲程式(台銀匯率)。',
        'RESUME_Java_content': '使用JSP實作出討論區網頁。',
        'RESUME_DB_content_1': '熟悉「SQL」指令。',
        'RESUME_DB_content_2': '熟悉「Postgres」、「SQL Server」管理。',
        'RESUME_Git_content': ' 熟悉基本指令，使用「Github」。',
        'RESUME_UX_content_1': '了解「The UI Stack」。',
        'RESUME_UX_content_2': '注重效能、簡單設計。',
        'RESUME_summary': '概要：',
        'RESUME_front_end_summary_1': '2年以上全端經驗。',
        'RESUME_front_end_summary_2': '實作過「響應式」、「多語系」、「企業入口網站」。',
        'RESUME_back_end_summary_1': '2年以上全端經驗。',
        'RESUME_back_end_summary_2': '實作「Web API」、「爬蟲程式」、「Web Server」。',
        'RESUME_others_summary_1': '2年以上管理資料庫經驗。',
        'RESUME_others_summary_2': '自主學習。',
        'RESUME_others_summary_3': 'Git基礎控管。',
        'CONTACT_thx_info_title': '感謝您的拜訪',
        'CONTACT_thx_info_content': '希望你會喜歡我的，如果有任何問題，歡迎與我聯繫。',
        'CONTACT_thx_info_signature': '-林建成',
    }
};

$(function() {
    $('.translate').click(function() {
        var lang = $(this).attr('id');

        $('.lang').each(function(index, element) {
            $(this).text(arrLang[lang][$(this).attr('key')]);
        });
    });
});